#!/bin/bash
# Day 2 Script: Your First Interactive Script
# Combine everything you've learned into a useful tool

echo "Day 2: Your First Interactive Script"
echo "Let's build something useful!"
echo

# Get user information
echo "=== USER INFORMATION ==="
read -p "Enter your name: " user_name
read -p "Enter your department: " department
read -p "Enter your role: " role

# Get system information using command substitution
current_date=$(date +%Y-%m-%d)
current_time=$(date +%H:%M:%S)
hostname_info=$(hostname)
current_user=$(whoami)
current_dir=$(pwd)

# Display collected information
echo
echo "=== INFORMATION SUMMARY ==="
echo "User Details:"
echo "  Name: $user_name"
echo "  Department: $department"
echo "  Role: $role"
echo
echo "System Details:"
echo "  System user: $current_user"
echo "  Hostname: $hostname_info"
echo "  Date: $current_date"
echo "  Time: $current_time"
echo "  Working directory: $current_dir"
echo

# Ask what type of report to generate
echo "=== REPORT OPTIONS ==="
echo "What type of report would you like to generate?"
echo "1. Basic system info"
echo "2. Detailed system report"
echo "3. Custom log entry"

read -p "Enter your choice (1-3): " choice

case $choice in
    1)
        echo
        echo "=== BASIC SYSTEM INFO ==="
        echo "Date: $(date)"
        echo "User: $(whoami)"
        echo "System: $(uname -s)"
        echo "Hostname: $(hostname)"
        ;;
    2)
        echo
        echo "=== DETAILED SYSTEM REPORT ==="
        echo "Generated by: $user_name ($role)"
        echo "Department: $department"
        echo "Date: $(date)"
        echo "System: $(uname -a)"
        echo "Uptime: $(uptime)"
        echo "Disk usage:"
        df -h | head -5
        echo "Memory usage:"
        free -h
        ;;
    3)
        read -p "Enter log message: " log_message
        log_file="custom_log_${current_date}.txt"
        echo "[$current_date $current_time] [$user_name] $log_message" >> "$log_file"
        echo "Log entry added to $log_file"
        ;;
    *)
        echo "Invalid choice. Please run the script again."
        ;;
esac

echo
echo "Script completed successfully!"
echo "You've built your first interactive script!"
