#!/bin/bash
# Day 2 Exercise: Command Substitution
# Learn to capture command output in variables

echo "Day 2: Command Substitution"
echo "Learn to capture command output!"
echo

pause() {
    echo
    read -p "Try this, then press Enter to continue..."
    echo
}

echo "=== PART 1: Basic Command Substitution ==="
echo
echo "You can store command output in variables:"
echo "Syntax: variable=\$(command)"
echo

echo "Let's capture today's date:"
echo "Command: today=\$(date)"
pause

today=$(date)
echo "Today's date stored in variable: $today"
echo

echo "=== PART 2: Useful Examples ==="
echo

echo "Current user:"
echo "Command: current_user=\$(whoami)"
pause
current_user=$(whoami)
echo "Current user is: $current_user"
echo

echo "Current directory:"
echo "Command: current_dir=\$(pwd)"
pause
current_dir=$(pwd)
echo "We are in: $current_dir"
echo

echo "System uptime:"
echo "Command: uptime_info=\$(uptime)"
pause
uptime_info=$(uptime)
echo "System uptime: $uptime_info"
echo

echo "=== PART 3: Processing Command Output ==="
echo

echo "Count files in current directory:"
echo "Command: file_count=\$(ls | wc -l)"
pause
file_count=$(ls | wc -l)
echo "Number of files: $file_count"
echo

echo "Get just the date part:"
echo "Command: just_date=\$(date +%Y-%m-%d)"
pause
just_date=$(date +%Y-%m-%d)
echo "Today's date: $just_date"
echo

echo "Get just the time:"
echo "Command: just_time=\$(date +%H:%M:%S)"
pause
just_time=$(date +%H:%M:%S)
echo "Current time: $just_time"
echo

echo "=== PART 4: Building Filenames ==="
echo

echo "Create timestamp-based filenames:"
timestamp=$(date +%Y%m%d_%H%M%S)
backup_name="backup_${timestamp}.tar"
log_name="system_${just_date}.log"

echo "Backup filename: $backup_name"
echo "Log filename: $log_name"
echo

echo "=== PART 5: System Information Gathering ==="
echo

echo "Let's gather system info with command substitution:"

hostname_info=$(hostname)
kernel_version=$(uname -r)
disk_usage=$(df -h / | tail -1 | awk '{print $5}')
memory_info=$(free -h | grep Mem | awk '{print $3 "/" $2}')

echo
echo "=== SYSTEM INFORMATION ==="
echo "Hostname: $hostname_info"
echo "Kernel: $kernel_version"
echo "Root disk usage: $disk_usage"
echo "Memory usage: $memory_info"
echo "Generated by: $current_user"
echo "Generated on: $today"
echo

echo "=== PART 6: Creating a System Report ==="
echo

report_file="system_report_${just_date}.txt"
echo "Creating system report: $report_file"

cat > "$report_file" << EOF
SYSTEM REPORT
=============
Generated: $(date)
By: $(whoami)
Hostname: $(hostname)
Kernel: $(uname -r)
Uptime: $(uptime)
Disk Usage: $(df -h / | tail -1)
Memory: $(free -h | grep Mem)
Current Directory: $(pwd)
Files in directory: $(ls | wc -l)
EOF

echo "Report created!"
echo "View with: cat $report_file"
echo

echo "What you learned:"
echo "   • \$(command) captures command output"
echo "   • Store output in variables for reuse"
echo "   • Build dynamic filenames with timestamps"
echo "   • Combine multiple commands for reports"
echo "   • Use command substitution in file creation"
echo
echo "Next: Run './scripts/first_script.sh'"
